
services:
  marcus_tails:
    build: .
    container_name: marcus_tails_code_test
    env_file: .env
    ports:
      - "6767:${APP_PORT}"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
